version: '3'
services:
  web:
    container_name: bycoders-model-web
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/bycoders-model/
    ports: ["3000:3000"]
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://@redis:6379/15
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports: ["5432:5432"]
