name: Run tests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: |
          bundle.tar.gz
          vendor/cache
        key: ${{ runner.os }}-bundle

    - name: Unzip bundle
      run: |
        test -f bundle.tar.gz && sudo tar -xzf bundle.tar.gz -C . && rm -f bundle.tar.gz
        echo "Tryed to unzip bundle"

    - name: Setup application
      run: docker-compose build --build-arg CI_BUILD=true

    - name: Setup test environment
      run: docker-compose run --rm web bundle exec rails db:create db:schema:load parallel:setup

    - name: Run tests
      run: docker-compose run --rm web bundle exec rails parallel:spec

    - name: Zip dependencies
      run: |
        docker ps
        docker-compose run web bundle package
        docker cp "$(docker ps -a | grep web | awk '{print $1}' | sed -n 1,1p)":/bundle .
        find bundle -name "*.c" -delete
        find bundle -name "*.o" -delete
        tar -zcf bundle.tar.gz bundle
